### PR TITLE
Skip downloading corelib for docs.rs

### LINKED ISSUE #144: Broken builds on docs.rs
### Problem

https://docs.rs/crate/scarb/0.1.0-rc.0/builds

### Steps

_No response_

### Possible Solution(s)

Silently skip downloading `corelib` from the network and mock it when `build.rs` is running in docs.rs build environment.

### Notes

_No response_

### Version

```text
`scarb 0.1.0-rc.0`
```

### PR DESCRIPTION
**Pull request by maciektr**
fix #144

### CODE REVIEW

File: scarb/build.rs [hunk 1]
```diff
@@ -70,6 +74,12 @@ fn download_core(rev: &str) {
     let out_dir = env::var("OUT_DIR").unwrap();
     let core_path = PathBuf::from_iter([&out_dir, &format!("core-{}", ident(rev))]);
 
+    if is_docs_rs() {
+        eprintln!("Docs.rs build detected. Skipping corelib download.");
+        println!("cargo:rustc-env=SCARB_CORE_PATH={}", core_path.display());
```
Comment (mkaput) [inline scarb/build.rs:79]: Have you tested that this does indeed build? It looks strange for me that it works if you didn't create a directory. We're using `include_dir!` on this path.

Comment (maciektr) [reply scarb/build.rs:79]: I've tested it locally by running `DOCS_RS=1 cargo build -vv`.

**Review by mkaput — APPROVED** [review]
LGTM. Please cherry-pick this to `release/0.1` branch after merging
