### PR TITLE
Fix dev-deps propagation of compiler plugins for ws members

### LINKED ISSUE #2118: Fix dev-deps propagation of compiler plugins for ws members

### PR DESCRIPTION
**Pull request by maciektr**
fixes #2118
This problem is analog to the https://github.com/software-mansion/scarb/issues/1535 (https://github.com/software-mansion/scarb/pull/1542). 
If a package (A) that is a ws member depends on another ws member (B), and (B) depends on some cairo plugin (C) as dev dependency, test CompilationUnit of (A) will include (C) as dependency of (B), although dev dependencies of (B) should not be propagated to the test compilation of (A) (both Cairo and Plugin dependencies).   

- **Add failing test for propagation of dev dep plugins from members of ws**
- **Do not propagate plugins that are dev dependencies of ws members to packages that depend on these ws members**

### CODE REVIEW

File: scarb/tests/metadata.rs [hunk 1]
```diff
@@ -398,6 +419,96 @@ fn dev_deps_are_not_propagated_for_ws_members() {
...
+            ("core".to_string(), vec!["core".to_string()]),
+            (
+                "dep2".to_string(),
+                vec![
+                    "core".to_string(),
+                    "dep2".to_string(),
+                    // Note that `cairo_test` is indeed a dev dependency of `dep2`,
+                    // but it's not propagated to the unit tests of `x`.
+                    // Only dev dependencies of the main component should be enabled.
+                    // "cairo_test".to_string()
```
Comment (DelevoXDG) [inline scarb/tests/metadata.rs:501]: This seems good, but I wonder if we should make `dep2` dev-depend on some **non-builtin** plugin, just so there's no confusion about builtins being handled differently.

**Review by DelevoXDG — APPROVED** [review]
A very minor comment, otherwise looks good

File: scarb/tests/metadata.rs (hunk 1 above)
Comment (maciektr) [reply scarb/tests/metadata.rs:501]: Added
