### PR TITLE
Pass absolute path to read workspace on Scarb new

### LINKED ISSUE #148: scarb new does not pass absolute path to read workspace check
### Problem

See steps, this warning shouldn't happen.

### Steps

```shell
$ scarb new hello_world
warn: compiling this new package may not work due to invalid workspace configuration

path (hello_world/Scarb.toml) is not absolute

Created `hello_world` package.

```

### Possible Solution(s)

_No response_

### Notes

_No response_

### Version

```text
v0.1.0-rc.0
```

### PR DESCRIPTION
**Pull request by maciektr**
fix #148

### CODE REVIEW

File: scarb/src/ops/new.rs [hunk 1]
```diff
@@ -1,7 +1,8 @@
-use anyhow::{bail, ensure, Context, Result};
+use anyhow::{anyhow, bail, ensure, Context, Result};
```
Comment (mkaput) [inline scarb/src/ops/new.rs:1]: Please squash commits

File: scarb/src/ops/new.rs [hunk 2]
```diff
@@ -100,11 +101,18 @@ fn mk(
     // Create project directory in case we are called from `new` op.
     fsx::create_dir_all(&path)?;
 
-    init_vcs(&path, version_control)?;
-    write_vcs_ignore(&path, config, version_control)?;
+    let canonical_path = if let Ok(canonicalize_path) = fs::canonicalize(&path) {
+        Utf8PathBuf::from_path_buf(canonicalize_path)
+            .map_err(|path| anyhow!("path `{}` is not UTF-8 encoded", path.display()))?
```
Comment (mkaput) [inline scarb/src/ops/new.rs:106]: please use methods from `PathBufUtf8Ext`

**Review by mkaput — CHANGES_REQUESTED** [review]

File: scarb/tests/e2e/new_and_init.rs [hunk 3]
```diff
@@ -146,6 +147,34 @@ fn new_existing() {
         "#});
 }
 
+#[test]
+fn new_no_abs_path_warning() {
```
Comment (mkaput) [inline scarb/tests/e2e/new_and_init.rs:151]:
```suggestion
fn issue_148() {
```

the issue description tells much more than this test name

File: scarb/src/ops/new.rs [hunk 4]
```diff
@@ -100,11 +102,17 @@ fn mk(
     // Create project directory in case we are called from `new` op.
     fsx::create_dir_all(&path)?;
 
-    init_vcs(&path, version_control)?;
-    write_vcs_ignore(&path, config, version_control)?;
+    let canonical_path = if let Ok(canonicalize_path) = fs::canonicalize(&path) {
```
Comment (mkaput) [inline scarb/src/ops/new.rs:105]:
```suggestion
    let canonical_path = if let Ok(canonicalize_path) = fsx::canonicalize(&path) {
```

I think I would rather stick to our wrapper at all costs, because who knows if we wouldn't want to slightly adjust its global behaviour in the future (for example, use `dunce` on Windows).

**Review by mkaput — APPROVED** [review]

**Review by mkaput — APPROVED** [review]
