### PR TITLE
Fix cairo-test dep missing warning 

### LINKED ISSUE #1603: Remove 'plugin not found' warning when inheriting workspace dependencies
### Problem

Main `scarb.toml`:
```
[workspace.dependencies]
cairo_test = "2.8.2"
```

Workspace's member `scarb.toml`:
```
[dev-dependencies]
cairo_test.workspace = true
```

Result in:
```
warn: `cairo_test` plugin not found
please add the following snippet to your Scarb.toml manifest:
\```
[dev-dependencies]
cairo_test = "2.8.2"
\```
```

### Steps

_No response_

### Possible Solution(s)

_No response_

### Notes

_No response_

### Version

```text
scarb 2.8.2 (a37b4cbfc 2024-09-09)
cairo: 2.8.2 (https://crates.io/crates/cairo-lang-compiler/2.8.2)
sierra: 1.6.0
```

### PR DESCRIPTION
**Pull request by maciektr**
fixes #1603

### CODE REVIEW

File: extensions/scarb-cairo-test/src/main.rs [hunk 1]
```diff
@@ -214,7 +216,7 @@ fn check_scarb_version(metadata: &Metadata) {
     }
 }
 
-fn check_cairo_test_plugin(metadata: &Metadata) {
+fn check_cairo_test_plugin(metadata: &Metadata, packages: &[PackageId]) {
     let app_version = env!("CARGO_PKG_VERSION").to_string();
     let warn = || {
         println!(
```
Comment (DelevoXDG) [inline extensions/scarb-cairo-test/src/main.rs:222]: Nit:

Unrelated, but: why are we not using scarb-ui here?

**Review by DelevoXDG — APPROVED** [review]
👍

File: extensions/scarb-cairo-test/src/main.rs (hunk 1 above)
Comment (DelevoXDG) [reply extensions/scarb-cairo-test/src/main.rs:222]: Ah, I see, already addressed in #1994 👍🏻
