### PR TITLE
Print diagnostics count for failed builds

### LINKED ISSUE #2565: Suggestion : report # of Warning and # of Errors after scarb build
### Problem

On the last line when compiling is failing : 

```

[...]
error: could not compile `package` due to previous error 
```

Please add something like 

```

[...]
error: could not compile `package`  || 12 errors, 25 warningss
```

### Proposed Solution

_No response_

### Notes

_No response_

### PR DESCRIPTION
**Pull request by maciektr**
fix #2565

### CODE REVIEW

File: utils/scarb-ui/src/counter.rs [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+        DiagnosticsCount {
+            errors_count: self.errors.load(Ordering::Acquire),
+            warnings_count: self.warnings.load(Ordering::Acquire),
+        }
+    }
+}
+
+pub struct DiagnosticsCount {
+    pub errors_count: usize,
+    pub warnings_count: usize,
```
Comment (mkaput) [inline utils/scarb-ui/src/counter.rs]: nit. field names duplicated struct name


```suggestion
    pub errors: usize,
    pub warnings: usize,
```

File: scarb/tests/proc_macro_v2_expand.rs [hunk 2]
```diff
@@ -1034,7 +1034,7 @@ fn code_mappings_preserve_attribute_error_on_inner_trait_locations_with_parser()
                     ^^^^^
             note: this error originates in the attribute macro: `some`
             
-            error: could not compile `hello` due to previous error
+            error: could not compile `hello` due to 1 previous error
```
Comment (mkaput) [inline scarb/tests/proc_macro_v2_expand.rs]:
```suggestion
            error: could not compile `hello` due to [..] previous error
```

would reduce test maintenance burden perhaps?
